### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by Poussinou** [calintat/units#7]
Could you please add this app to F-Droid, a free and open source appstore? https://f-droid.org/
You can find some doc on the website of F-Droid... :)

It will attract the attention on your app and help people who don't use the Play Store like me !

Thanks

Edit : I opened a Request For Packaging [here](https://gitlab.com/fdroid/rfp/issues/611)

**Comment by IzzySoft** [comment]
> and help people who don't use the Play Store like me !

and me :wink:

to get your app into the official repo, we'd need a build flavor without `vending.BILLING`, though. If you meanwhile would like to see your app in [my repo](https://apt.izzysoft.de/fdroid/repo), attaching the `.apk` to your `releases/` would enable me to pick it.

**Comment by IzzySoft** [comment]
@calintat I see there's a commit that already removed vending.BILLING. Will you tag another release? There have been quite a bunch of commits after the last one.

**Comment by IzzySoft** [comment]
@calintat No response at all – does that mean you no longer maintain this project? Is it abandoned?

**Comment by Poussinou** [comment]
Probably abandonware, [we won't include this app](https://gitlab.com/fdroid/rfp/issues/611), so I'm closing this issue.
